### ISSUE TITLE
Missing Water Years Causes Issues

### ISSUE THREAD

**Issue by NathanEne** [camcarpenter6/Alternate-Ruleset-FFC-BETA#1]
The below 'if' block seems to assume that the previous entry in the array represents the previous water year
https://github.com/camcarpenter6/Alternate-Ruleset-FFC-BETA/blob/dbfbe953b3681546d51ee783781c57487ab942f1/Utils/Fall_and_Wet_Timing.R#L124-L129

The way that the water years are processed:
https://github.com/camcarpenter6/Alternate-Ruleset-FFC-BETA/blob/dbfbe953b3681546d51ee783781c57487ab942f1/Calculations/Get_metrics.R#L25

leads to this assumption being false when there are missing water years in the source dataset, such as [this file](https://github.com/user-attachments/files/16700409/10251300_cleaned.csv) which has many missing water years. The result of this is the current water year and the previous one within the array being stitched together for the remainder of the fall peak criteria evaluation even though they can be very temporally far apart.

This same assumption is present in other parts of the code:
https://github.com/camcarpenter6/Alternate-Ruleset-FFC-BETA/blob/dbfbe953b3681546d51ee783781c57487ab942f1/Utils/Fall_and_Wet_Timing.R#L73

I apologize if this is intended behaviour or if this version of the FFC is not intended to be run on data with gaps in the water years

**Comment by camcarpenter6** [comment]
Hello,

You are correct; this is how this version of the calculator is meant to operate. The code is only looking at the previous water year that had data. If there is a data gap then it will look at the last year with data. 

If a water year has some data but does not qualify for calculation then it should not produce metrics. In this case, the calculator should still try to use the previous water year, but if necessary it will look backward to older water years to get the information needed.
